python-driven-cavity:
    stage: test
    image: "docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/ubuntu:bionic-python3"
    before_script:
        - pip3 install scipy matplotlib tikzplotlib
    script:
        - cp -r scripts/reference-data scripts/results
        - cd scripts
        - source runme.sh
    artifacts:
        paths:
            - scripts/Figures/*.tex
            - scripts/Figures/*.pdf
            - scripts/Figures/*.vtu
